### ISSUE TITLE
Configurable Colours

### ISSUE THREAD

**Issue by JustKato** [JustKato/DamageDisplay#5]
Add in new configurations for:
```yml
# This is just a nice listing I made, doesn't have to be the same names in the config, just tha YAML is readable

floatingText:
  colour: "#ff0000"
  bgColour: "#00000020"
actionBar:
  dealt: # Damage Dealt
    format: "💀"
    color: "YELLOW"
  taken: # Damage Taken
    format: "💀"
    color: "RED"
```

Something like the above I think would go a long way.
